// Bundles the web game (../index.html + ../js + ../css + vendored three) into ONE self-contained HTML string
// that the WebView loads from memory — works offline, no local file access needed.
// Also emits the list of valid product IDs (from js/catalog.js) for the native bridge allowlist.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { resolve, dirname } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const out = resolve(here, '../src');
mkdirSync(out, { recursive: true });

const result = await build({
  entryPoints: [resolve(root, 'js/main.js')], bundle: true, minify: true, format: 'iife', write: false, target: 'es2020',
  alias: { three: resolve(root, 'vendor/three.module.js') }, legalComments: 'none', logLevel: 'warning',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const css = readFileSync(resolve(root, 'css/style.css'), 'utf8');

// Same policy as the web build, but the inline bundle is allowed by hash instead of 'self'.
const { policy, sha256 } = await import(pathToFileURL(resolve(root, 'scripts/csp.mjs')).href);
const jsHash = createHash('sha256').update(js).digest('base64');
const csp = policy([jsHash]).replace("script-src 'self'", "script-src");

let html = readFileSync(resolve(root, 'index.html'), 'utf8');
html = html.replace(/<!-- csp:start -->[\s\S]*?<!-- csp:end -->/, `<meta http-equiv="Content-Security-Policy" content="${csp}">`)
  .replace(/<script type="importmap">[\s\S]*?<\/script>/, '')
  .replace(/<link rel="stylesheet" href="css\/style.css">/, `<style>${css}</style>`)
  .replace(/<script type="module" src="js\/main.js"><\/script>/, () => `<script>${js}</script>`);
if (!html.includes(jsHash.slice(0, 8)) && !html.includes('<script>')) throw new Error('bundle injection failed');

writeFileSync(resolve(out, 'gameHtml.generated.ts'), `// AUTO-GENERATED by scripts/build-game.mjs — do not edit.\nexport const GAME_HTML = ${JSON.stringify(html)};\n`);
const { PRODUCTS } = await import(pathToFileURL(resolve(root, 'js/catalog.js')).href);
writeFileSync(resolve(out, 'productIds.generated.ts'), `// AUTO-GENERATED from js/catalog.js\nexport const PRODUCT_IDS: readonly string[] = ${JSON.stringify(Object.keys(PRODUCTS))};\n`);
console.log(`game bundled: ${(html.length / 1024).toFixed(0)} KB, ${Object.keys(PRODUCTS).length} products`);
